[[normal-60.monitors]]
name = "eDP-1"

[normal-60.monitors.state.Enabled]
dimensions = [2560, 1600]
position = [0, 0]
rerfresh_rate = 60
scaling = 1.25

[[normal-60.monitors]]
name = "HDMI-A-1"
state = "Disabled"

[[normal-165.monitors]]
name = "eDP-1"

[normal-165.monitors.state.Enabled]
dimensions = [2560, 1600]
position = [0, 0]
rerfresh_rate = 165
scaling = 1.25

[[normal-165.monitors]]
name = "HDMI-A-1"
state = "Disabled"


[[home.monitors]]
name = "eDP-1"

[home.monitors.state.Enabled]
dimensions = [2560, 1600]
position = [0, 1080]
rerfresh_rate = 165
scaling = 1.25

[[home.monitors]]
name = "HDMI-A-1"

[home.monitors.state.Enabled]
dimensions = [1920, 1080]
position = [0, 0]
rerfresh_rate = 75
scaling = 1

# [[home-one-monitor.monitors]]
# name = "HDMI-A-1"
#
# [home-one-monitor.monitors.state.Enabled]
# dimensions = [1920, 1080]
# position = [0, 0]
# rerfresh_rate = 75
# scaling = 1
#
# [[home-one-monitor.monitors]]
# name = "eDP-1"
# state = "Disabled"
#
